package com.example.android_4_1_libraries.presenter.listProfile

import com.example.android_4_1_libraries.view.listProfile.UserItemViewProfile

interface IUserListPresenterProfile : IListPresenterProfile<UserItemViewProfile>